---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: docker
  image: plugins/docker:latest
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: markis/backyard-brawl
    tags: latest
  when:
    branch: master
