[project]
name = "brawl"
version = "0.0.1"
authors = ["Markis Taylor <m@rkis.cc>"]
license = "MIT"
readme = "README.md"

[dependencies]
sleeper-api-wrapper="1.0.7"

[build-system]
requires = ["setuptools", "wheel"]
